/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exercicioCrud.View.Cliente;


import exercicioCrud.Controller.ClienteController;
import exercicioCrud.View.DialogBox.ConfirmaDialog;
import exercicioCrud.View.DialogBox.InformativoDialog;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author Frede
 */

    

public class JanClienteLista extends javax.swing.JFrame {
    private static DefaultTableModel defaultModel;
    private static ClienteController cliC;
    
    /**
     * Creates new form JanClienteLista
     */
    public JanClienteLista() {
        initComponents();
        cliC = new ClienteController();
        defaultModel = (DefaultTableModel) jTableJanCliente.getModel();
        carregarLista();
//        jTableJanCliente.setModel(defaultModel);
    }
public static void carregarLista(){
        if(defaultModel == null){
            return;
        }
        defaultModel.setRowCount(0);
        defaultModel.setColumnCount(0);
        
        try {
            ResultSet rst = cliC.returnAll();
            int colNo = rst.getMetaData().getColumnCount();
            for (int i = 1; i <= rst.getMetaData().getColumnCount(); i++) {
                defaultModel.addColumn(rst.getMetaData().getColumnLabel(i));
            }
            
            while(rst.next()){
                Object[] obj = new Object[colNo];
                for(int i = 0; i < colNo; i++) {
                    obj[i] = rst.getObject(i+1);
                }
                defaultModel.addRow(obj);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableJanCliente = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTableJanCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableJanCliente);

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(56, 56, 56)
                .addComponent(jButtonEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed

                int row = jTableJanCliente.getSelectedRow();
        if(row == -1){
            InformativoDialog.msgItemNaoSelecionado("Editar", true);
        }else{
            int id =  (jTableJanCliente.getValueAt(row, 0) != null) ? Integer.parseInt(jTableJanCliente.getValueAt(row, 0).toString()) : 0;
            String nome =  (jTableJanCliente.getValueAt(row, 1) != null) ? jTableJanCliente.getValueAt(row, 1).toString() : "";
            String cpf =  (jTableJanCliente.getValueAt(row, 2) != null) ? jTableJanCliente.getValueAt(row, 2).toString() : "";
            String endereco =  (jTableJanCliente.getValueAt(row, 3) != null) ? jTableJanCliente.getValueAt(row, 3).toString() : "";
            String email =  (jTableJanCliente.getValueAt(row, 4) != null) ? jTableJanCliente.getValueAt(row, 4).toString() : "";
            cliC.getCliente().setId(id);
            cliC.getCliente().setNome(nome);
            cliC.getCliente().setCpf(cpf);
            cliC.getCliente().setEndereco(endereco);
            cliC.getCliente().setEmail(email);
            JanClienteEditar ce = new JanClienteEditar(cliC.getCliente());
            ce.setLocationRelativeTo(this);
            ce.setVisible(true);
            
            
        }
        
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JanClienteEditar jc = new JanClienteEditar();
        jc.setLocationRelativeTo(this);
        jc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int row = jTableJanCliente.getSelectedRow();
        if(row == -1){
            InformativoDialog.msgItemNaoSelecionado("Excluir", true);
        }else{
            String nome =  (jTableJanCliente.getValueAt(row, 1) != null) ? jTableJanCliente.getValueAt(row, 1).toString() : "";
            if(ConfirmaDialog.msgConfimarExclusao(nome)){
                cliC.excluir(Integer.parseInt(jTableJanCliente.getValueAt(row, 0).toString()));
                JanClienteLista.carregarLista();
            }
            
            
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanClienteLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanClienteLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanClienteLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanClienteLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanClienteLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableJanCliente;
    // End of variables declaration//GEN-END:variables
}
