/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jasper.View.Automoveis;

import com.mysql.jdbc.Connection;
import jasper.Conn.BD;
import jasper.Controller.AutomovelController;
import jasper.Migrations.FabricanteMigration;
import jasper.Migrations.AutomovelMigration;
import jasper.Migrations.MigrationAll;
import jasper.View.DialogBox.ConfirmaDialog;
import jasper.View.DialogBox.InformativoDialog;
import jasper.View.Fabricante.ListaFabricantes;
import java.io.File;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.commons.collections.bidimap.AbstractBidiMapDecorator;

/**
 *
 * @author Frede
 */
public class ListaAutomoveis extends javax.swing.JFrame {

    /**
     * Creates new form Lista
     */
    private static ResultSet rst;
    private static DefaultTableModel defaultModel;
    private static AutomovelController ctr;
    private static Vector cab ;
    Connection con = null;
    public static final String pdf = System.getProperty("user.dir") + "/MyReports/ExeSete.pdf";

    public static final String relatorioGeral = System.getProperty("user.dir") + "/src/MyReports/Geral.jasper";
    public static final String relatorioAgrupadoGeral = System.getProperty("user.dir") + "/src/MyReports/GroupGeral.jasper";
    public static final String relatorioModelo = System.getProperty("user.dir") + "/src/MyReports/ModeloPesquisavel.jasper";

   
    
    public static void carregarLista(){
        System.out.println("Esse é r gerla " +relatorioGeral);
        defaultModel.setRowCount(0);
        defaultModel.setColumnCount(0);
        try {
            cab = new Vector();
            ResultSet rst = ctr.returnAll();
            int colNo = rst.getMetaData().getColumnCount();
            for (int i = 1; i <= rst.getMetaData().getColumnCount(); i++) {
//                defaultModel.addColumn(rst.getMetaData().getColumnName(i));
                getDefaultModel().addColumn(rst.getMetaData().getColumnLabel(i));
                
            }
            
            while(rst.next()){
                Object[] obj = new Object[colNo];
                for(int i = 0; i < colNo; i++) {
                    obj[i] = rst.getObject(i+1);
                }
                getDefaultModel().addRow(obj);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
    }
    
    public Map constroiParametroAutomovel(){
        Map p = new HashMap();
        int id = Integer.parseInt(JOptionPane.showInputDialog(
                this,
                "Digite o codigo do modelo do veiculo",
                "Entrada",
                JOptionPane.QUESTION_MESSAGE
        ));
        p.put("IdAutomovel", id);
        return p;
    }
    public ListaAutomoveis() {
        BD bd = new BD();
        initComponents();
        MigrationAll.init();
        ctr = new AutomovelController();
        defaultModel = (DefaultTableModel) jTableListaModelos.getModel();
        this.carregarLista();
        jTableListaModelos.setModel(getDefaultModel());
        con = (Connection) bd.getConnection();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaModelos = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemFabricanteVer = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemFabricanteVer1 = new javax.swing.JMenuItem();
        jMenuItemFabricanteVer2 = new javax.swing.JMenuItem();
        jMenuItemFabricanteVer3 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableListaModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableListaModelos);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jMenu2.setText("Arquivo");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Modelo");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Fabricante");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItemFabricanteVer.setText("Ver / Editar");
        jMenuItemFabricanteVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFabricanteVerActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemFabricanteVer);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatorio");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItemFabricanteVer1.setText("Geral");
        jMenuItemFabricanteVer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFabricanteVer1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemFabricanteVer1);

        jMenuItemFabricanteVer2.setText("Agrupado por fabricante");
        jMenuItemFabricanteVer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFabricanteVer2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemFabricanteVer2);

        jMenuItemFabricanteVer3.setText("Modelo por id");
        jMenuItemFabricanteVer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFabricanteVer3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemFabricanteVer3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonPlus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int row = jTableListaModelos.getSelectedRow();
        if(row == -1){
            InformativoDialog.msgItemNaoSelecionado("Editar", true);
        }else{
            int id = Integer.parseInt(jTableListaModelos.getValueAt(row, 0).toString());
            String modelo = jTableListaModelos.getValueAt(row, 1).toString();
            int idfab = Integer.parseInt(jTableListaModelos.getValueAt(row, 2).toString());
            float gasolina = Float.parseFloat(jTableListaModelos.getValueAt(row, 3).toString());
            float alcool = Float.parseFloat(jTableListaModelos.getValueAt(row, 4).toString());
            float diesel = Float.parseFloat(jTableListaModelos.getValueAt(row, 5).toString());
            String fabricante = jTableListaModelos.getValueAt(row, 6).toString();
            
            ctr.getAutomovel().setId(id);
            ctr.getAutomovel().setModelo(modelo);
            ctr.getAutomovel().getFabricante().setId(idfab);
            ctr.getAutomovel().getFabricante().setNome(fabricante);
            ctr.getAutomovel().setGasolina_efici(gasolina);
            ctr.getAutomovel().setAlcool_efici(alcool);
            ctr.getAutomovel().setDiesel_efici(diesel);
            CadastrarAutomovel cadA = new CadastrarAutomovel(ctr);
            cadA.setLocationRelativeTo(this);
            cadA.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int row = jTableListaModelos.getSelectedRow();
        if( row == -1 ){
            InformativoDialog.msgItemNaoSelecionado("Excluir", true);
        }else{
            if(ConfirmaDialog.msgConfimarExclusao(jTableListaModelos.getValueAt(row, 1).toString())){
                int id = Integer.parseInt(jTableListaModelos.getValueAt(row, 0).toString());
                ctr.getAutomovel().setId(id);
                if(ctr.delete() == 1){
                    getDefaultModel().removeRow(row);
                }
            }
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
//        ConfirmaDialog.msgConfimarExclusao();
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItemFabricanteVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFabricanteVerActionPerformed
        ListaFabricantes lf = new ListaFabricantes();
        lf.setLocationRelativeTo(this);
        lf.setVisible(true);
    }//GEN-LAST:event_jMenuItemFabricanteVerActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        CadastrarAutomovel ca = new CadastrarAutomovel();
        ca.setLocationRelativeTo(this);
        ca.setVisible(true);
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItemFabricanteVer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFabricanteVer1ActionPerformed

        JasperPrint impr;
        try {
            BD bd = new BD();
            bd.BDInit();
            impr = JasperFillManager.fillReport(relatorioGeral, null, bd.getConnection());
            JasperViewer.viewReport(impr, false);
            //JasperViewer jasperViewer = new JasperViewer( impr, false );
//	    jasperViewer.setVisible( true );
	   
        } catch (JRException ex) {
            System.out.println("erro "+ ex);
        }
    }//GEN-LAST:event_jMenuItemFabricanteVer1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItemFabricanteVer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFabricanteVer2ActionPerformed
        
        JasperPrint impr;
        try {
            BD bd = new BD();
            bd.BDInit();
            impr = JasperFillManager.fillReport(relatorioAgrupadoGeral, null, bd.getConnection());
            JasperViewer.viewReport(impr, false);
	   
        } catch (JRException ex) {
            System.out.println("erro "+ ex);
        }
    }//GEN-LAST:event_jMenuItemFabricanteVer2ActionPerformed

    private void jMenuItemFabricanteVer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFabricanteVer3ActionPerformed
        JasperPrint impr;
        try {
            BD bd = new BD();
            bd.BDInit();
            Map p = constroiParametroAutomovel();
            impr = JasperFillManager.fillReport(
                    relatorioModelo, 
                    p, 
                    bd.getConnection()
            );
            JasperViewer.viewReport(impr, false);
	   
        } catch (JRException ex) {
            System.out.println("erro "+ ex);
        }
    }//GEN-LAST:event_jMenuItemFabricanteVer3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaAutomoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaAutomoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaAutomoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaAutomoveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaAutomoveis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemFabricanteVer;
    private javax.swing.JMenuItem jMenuItemFabricanteVer1;
    private javax.swing.JMenuItem jMenuItemFabricanteVer2;
    private javax.swing.JMenuItem jMenuItemFabricanteVer3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaModelos;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the defaultModel
     */
    public static DefaultTableModel getDefaultModel() {
        return defaultModel;
    }
}
